### ISSUE TITLE
List of missing 2-letter words, which play a major role in scrabble and are listed in Rechtschreibeduden release 28

### ISSUE THREAD

**Issue by hippler** [enz/german-wordlist#9]
AD
    AI
    AR
    BI
    DO
    ET
    FA
    GO
    HA
    HE
    HI
    HM
    HO
    ID
    LA
    MI
    MY
    NY
    OH
    SI
    ST
    TI
    TÖ
    UD
    UH
    UI
    WU

**Comment by enz** [comment]
Could you provide the words using their unmodified spellings? The lists in this project don't use transformation to all-uppercase because Tanglet automatically creates links to dictionaries. Also, the word "WU" is illegal according the Scrabble tournament checker (linked from the Wiki page of this project). Maybe the tournament checker is not up to date but could you please verify that it is really a legal word in Scrabble?

**Comment by hippler** [comment]
Hello Markus,

Thanks for your fast reply.

You are right, WU is not in the Rechtschreibeduden release 28.

I checked WU and all other 2 letter words using SuperDic-Checker
[ https://scrabble-info.de/wortlisten/superdic-checker/ <https://scrabble-info.de/wortlisten/superdic-checker/> ].

Below the corrected 2 letter list, following the DUDEN online check (best effort):

[ https://www.duden.de/rechtschreibung <https://www.duden.de/rechtschreibung> ]

ad, Ad
Ai
Ar
bi
do
et
fa
Go
ha
he
hi
hm
ho
Id, ID
la
mi
My
Ny
oh, Oh
si
st
ti
Tö
Ud
uh
ui

Cheers,

Stefan

**Comment by enz** [comment]
Thanks. I also added the plural forms for the nouns. The only plural that was not legal according to the tournament checker was "Ads", but I added it anyway because [according to the online Duden](https://www.duden.de/rechtschreibung/Ad), "Ad" is a German noun and its plural is "Ads".

**Comment by enz** [comment]
I also added "Wu(s)" as it meets the criterion for our list to be listed in the Duden and not to violate the general Scrabble rules.
